test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon: &amazon
  service: S3
  access_key_id: <%= Rails.application.secrets.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.secrets.aws[:secret_access_key] %>
  region: <%= Rails.application.secrets.aws[:region] %>

amazon_public:
  <<: *amazon
  bucket: <%= Rails.application.secrets.aws[:bucket_public] %>
  public: true

amazon_private:
  <<: *amazon
  bucket: <%= Rails.application.secrets.aws[:bucket_private] %>
